### ISSUE TITLE
Run KEDA with readOnlyRootFilesystem

### ISSUE THREAD

**Issue by lambohamp** [kedacore/charts#103]
Hi,

I am running KEDA v2.0.0 and trying to set `readOnlyRootFilesystem: true` due to security concerns, but I am getting the following error from `keda-operator-metrics-apiserver`:

```
E1117 09:29:17.080262       1 main.go:116] keda_metrics_adapter "msg"="unable to run external metrics adapter" "error"="error creating self-signed certificates: open apiserver.local.config/certificates/apiserver.crt: read-only file system" 
```

Is there a way to enable read only fs for KEDA?

Thanks.

**Comment by tomkerkhove** [comment]
Adding @zroubalik but that might require a change

**Comment by zroubalik** [comment]
Metrics adapter needs certificates. If there aren't any attached, the metrics adapter generates self signed ones.

You can mount a secret/configmap with CA, cert and key. Then you can reference it in the Metrics Adapter Deployment, in the container args section:
```yaml
       args:
            - '--client-ca-file=/cabundle/service-ca.crt'
            - '--tls-cert-file=/certs/tls.crt'
            - '--tls-private-key-file=/certs/tls.key'
```

**Comment by lambohamp** [comment]
Thank you @zroubalik , I will give it a try.

**Comment by tomkerkhove** [comment]
This sounds like a good FAQ opportunity, would you mind contributing this @lambohamp?

You can find guidance on https://github.com/kedacore/keda-docs#add-new-frequently-asked-question-faq
