### ISSUE TITLE
CRDs are failing to install on K8s v1.15.11

### ISSUE THREAD

**Issue by lekspyl** [kedacore/charts#104]
Hello,

Looks like #94 breaks compatibility with Kubernetes versions prior to 1.16. I was trying to install the chart but I'm getting
```
Error: failed to install CRD crds/scaledjobs.keda.sh.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1"
```

I'm running EKS v1.15.11.
Was this breaking change expected?

**Comment by tomkerkhove** [comment]
Yes, it's documented in [our FAQ](https://keda.sh/docs/2.0/faq/)

**Comment by brunooliveiramac** [comment]
We are facing same issue. Is this related to this PR? https://github.com/kedacore/charts/pull/94 ot this one https://github.com/kedacore/charts/pull/101

We are using helm 2 and kubernetes 1.18

**Comment by Fel3180** [comment]
I have the same problem, in my case the keda-operator is reporting the following error:

E1119 20:10:04.006257       1 reflector.go:178] pkg/mod/k8s.io/client-go@v0.18.8/tools/cache/reflector.go:125: Failed to list *v
1alpha1.ScaledObject: the server could not find the requested resource (get scaledobjects.keda.sh)****

**Comment by tomkerkhove** [comment]
Helm 2 is no longer supported unfortunately since it is out of support

**Comment by lekspyl** [comment]
I think this clears thing out for everyone; gonna stick to v1.5.0 for now. Thank you!
