### ISSUE TITLE
Provide capability to configure HTTP timeouts

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/charts#109]
Provide capability to configure HTTP timeouts by configuring `KEDA_HTTP_DEFAULT_TIMEOUT` environment variable. (see https://github.com/kedacore/keda/pull/1251#issuecomment-739836264)

This is a follow-up for https://github.com/kedacore/keda/issues/1133

**Comment by arschles** [comment]
@tomkerkhove I think this is [done](https://github.com/kedacore/keda/blob/69b69ba67095767d503fe6fd1e58db6886fe584f/main.go#L113)?

**Comment by tomkerkhove** [comment]
Yes you did this through - https://github.com/kedacore/charts/pull/90
