### ISSUE TITLE
Provide resource requests/limits for KEDA deployment

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/charts#112]
Provide resource requests/limits for KEDA deployment

**Comment by zroubalik** [comment]
These values are in yaml, so probably just add them to the template is enough: https://github.com/kedacore/keda/blob/2a2987ab0f6020cffa9e75e18005469ca3aaf426/config/manager/manager.yaml#L37-L42

**Comment by tomkerkhove** [comment]
They are not used as part of our Helm chart for now: https://github.com/kedacore/charts/blob/master/keda/values.yaml#L93

Will move them over as defaults as well.

Note to self, metrics service limits are here: https://github.com/kedacore/keda/blob/2a2987ab0f6020cffa9e75e18005469ca3aaf426/config/metrics-server/deployment.yaml

**Comment by tomkerkhove** [comment]
This should follow our documented limits/requests: https://keda.sh/docs/latest/operate/cluster/

**Comment by JorTurFer** [comment]
Should we split the resources in `keda` and `metricsApiServer`? 
I guess that the operator could need different resources than the metrics server, or not  :wink:

**Comment by tomkerkhove** [comment]
They are currently the same but best to separate in case we need to change them later on indeed.

**Comment by JorTurFer** [comment]
OMW

**Comment by zroubalik** [comment]
+1 for separation
