### ISSUE TITLE
wrong URL repository 

### ISSUE THREAD

**Issue by guilhermepozo** [kedacore/charts#131]
https://github.com/kedacore/charts/blob/56d54095ea07e2a2a52c0e76eea8f692a7c5a3f6/keda/values.yaml#L7

**Comment by guilhermepozo** [comment]
Wrong repository URL at chart default values.yaml

**Comment by tomkerkhove** [comment]
This is not the wrong image URL but our new one, see #127 & kedacore/governance#16.

I've missed the README, though, which is fixed in 	https://github.com/kedacore/charts/pull/132

**Comment by tomkerkhove** [comment]
Oh now I see
