### ISSUE TITLE
Add ability to configure logging zap encoder via values

### ISSUE THREAD

**Issue by sharkymcdongles** [kedacore/charts#144]
Currently this is hardcoded to console:

https://github.com/kedacore/charts/blob/master/keda/templates/12-keda-deployment.yaml#L56

However this can be set to json per this:

https://github.com/kedacore/keda/blob/main/BUILD.md#miscellaneous

**Comment by tomkerkhove** [comment]
Ok for you @zroubalik?

Are you willing to contribute this @sharkymcdongles?

**Comment by zroubalik** [comment]
> Ok for you @zroubalik?

Absolutely :)

**Comment by sharkymcdongles** [comment]
> Ok for you @zroubalik?
> 
> Are you willing to contribute this @sharkymcdongles?

Ya I can submit PR shortly.

**Comment by sharkymcdongles** [comment]
https://github.com/kedacore/charts/pull/145

@tomkerkhove

**Comment by tomkerkhove** [comment]
Thank you!
