### ISSUE TITLE
Allow the http-add-on chart to use the 'latest' tag

### ISSUE THREAD

**Issue by arschles** [kedacore/charts#150]
Currently the HTTP add on chart defaults to a [`vX.Y.Z` tag](https://github.com/kedacore/charts/blob/914c60da8d2805be03f562b3720307683af4d4cd/http-add-on/templates/deployment.yaml#L53). We should allow users to install the `latest` tag as well. This

### Use-Case

Users who would like to stay on the latest stable release may want to just use `latest` (along with an `ImagePullPolicy` of `Always`) to stay up to date.

### Specification

- [ ] The [deployment's image name](https://github.com/kedacore/charts/blob/914c60da8d2805be03f562b3720307683af4d4cd/http-add-on/templates/deployment.yaml#L53) is fixed to not always prefix with `v`
- [ ] The [values.yaml](https://github.com/kedacore/charts/blob/master/http-add-on/values.yaml#L20-L22) file is changed to add a `tag` field, similar to how KEDA's [values.yaml](https://github.com/kedacore/charts/blob/master/keda/values.yaml#L9) does it

cc/ @khaosdoctor

**Comment by khaosdoctor** [comment]
On it!
