### ISSUE TITLE
Support PrometheusRules as part of the Chart 

### ISSUE THREAD

**Issue by avivgold098** [kedacore/charts#156]
### Use-Case

Allow the Keda chart users to define `PrometheusRules` object as part of the Chart, for alerting purposes.

### Specification
Includes `PrometheusRules` [Object](https://github.com/prometheus-operator/prometheus-operator#customresourcedefinitions) Object template, to enhance the Keda internal monitoring.

**Comment by avivgold098** [comment]
Coralogix platform team can assist with the implementation :)

**Comment by tomkerkhove** [comment]
That would be great if you can contribute it, thank you!

**Comment by avivgold098** [comment]
@tomkerkhove  https://github.com/kedacore/charts/pull/157 is available for review
