### ISSUE TITLE
Helm 3 install failed 

### ISSUE THREAD

**Issue by jiayanguo** [kedacore/charts#18]
When I am trying to install Keda in minikube via Helm3, it throws below error.
```
helm install keda kedacore/keda --namespace keda                                                                                  
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
manifest_sorter.go:175: info: skipping unknown hook: "crd-install"
NAME: keda
LAST DEPLOYED: Sun Nov 24 18:22:12 2019
NAMESPACE: keda
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

**Comment by catirado** [comment]
Any news on that? The same problem here because the `skipping unknown hook: "crd-install"` throws an error in the CI and this makes the job fail.

I was trying to follow the proposed changes in #17, but I see that the related to this issue were removed because of the need for backward compatibility with Helm 2. Also in #20 that the issue of labels is resolved as well.

Any chance of getting it back?

Thank you so much

**Comment by tomkerkhove** [comment]
We are keeping Helm 2 support for now as we have a lot of customers still using it to date - https://github.com/kedacore/charts/issues/40

In the past it just gave a warning instead of an error which is odd. Is it specific to your CI or not?

**Comment by tomkerkhove** [comment]
Happy to help and sorry for the pain!

**Comment by channeladam** [comment]
If it isn't an actual error, it shouldn't be logged to stderr. Setting fail on stderr to false could hide other possible problems - this is not a safe workaround.

**Comment by tomkerkhove** [comment]
I fully agree @channeladam!

Given Helm [just did their final Helm 2.x release](https://github.com/helm/helm/releases/tag/v2.16.10), [they published that it's no longer being updated](https://helm.sh/blog/helm-v2-deprecation-timeline/) and we have KEDA 2.0 coming up I think it's time to move on.

Thoughts on removing Helm 2.0 support and close this issue @jeffhollan @ahmelsayed @zroubalik @anirudhgarg ?

**Comment by tomkerkhove** [comment]
@tbickford Is it correct that you had a solution for this?

**Comment by tomkerkhove** [comment]
Actually I think it's time to move off: https://twitter.com/technosophos/status/1306640949896912901

**Comment by tbickford** [comment]
@tomkerkhove Apologies - I have been on PTO. This PR https://github.com/kedacore/charts/pull/60 should allow for both Helm 2 and 3 compatibility

**Comment by tomkerkhove** [comment]
We're removing support for Helm v2.x being tracked in https://github.com/kedacore/charts/issues/81.

**Comment by tomkerkhove** [comment]
Fixed in https://github.com/kedacore/charts/releases/tag/v2.0.0
