### ISSUE TITLE
Add support to set `KEDA_HTTP_DEFAULT_TIMEOUT` in metrics server

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/charts#180]
We have KEDA deployed using helm, and we use several RabbitMQ Scalers with regex selection. Our problem is that some triggers needs to customize the `KEDA_HTTP_DEFAULT_TIMEOUT` to extend the default values because get the queues using regex needs 5-10 seconds in some cases (we have more than 1k queues in some clusters).  

Right now it's supported the configuration of it in the operator but not in the metric server

I can open a PR with the change if you agree it

**Comment by tomkerkhove** [comment]
Sounds good, thanks!

**Comment by zroubalik** [comment]
Would you mind adding this env (with the default value) to the kedacore/keda as well? Both Operator and Metrics server? Thanks!

**Comment by JorTurFer** [comment]
> Would you mind adding this env (with the default value) to the kedacore/keda as well? Both Operator and Metrics server? Thanks!

I will take a look there also, np, but I think that I am using it right now 😆 . 
At least, I edited the deployment manually and now I'm not getting any error but idk if the RabbitMQ cluster is responding faster for idk why xD

**Comment by zroubalik** [comment]
Yeah, it is being set there, but I mean to add it to `Deployment` spec, so it is there "visible" for users.

**Comment by JorTurFer** [comment]
Sorry but I don't get the requirement :/ 
do you want to set it as default in `kedacore/keda` for example in the Dockerfile? 
I'm a bit confused with the last message about adding it to `Deployment` spec, in the chart?

**Comment by zroubalik** [comment]
The Helm Chart entry is being applied to Operator `Deployment` and similar place for Metrics Server:
https://github.com/kedacore/keda/blob/fe032ccc41f1af1aa4dcdcf4f1d05bba9150fdbf/config/manager/manager.yaml#L57

I wanted to put the ENV in there as well, for users that don't use Helm Charts to install KEDA. So the Env is visible there. But it is not important and maybe we can skip that for now.

**Comment by JorTurFer** [comment]
oh... I got it! I will do it also as part of this task :)

**Comment by JorTurFer** [comment]
I think this issue should still be opened, the main goal is not merged yet (support it in helm).
wdyt @zroubalik ?

**Comment by zroubalik** [comment]
Yeah, GitHub closed this automatically. thanks!
