### ISSUE TITLE
Arg '-leader-elect' in '12-keda-deployment.yaml' template is no longer supported.

### ISSUE THREAD

**Issue by theboyisno-1** [kedacore/charts#191]
When I am trying to deploy Keda helm chart from master branch (at the time of writing this), `keda-operator` pod is going in crashloop with below error:
```SHELL
flag provided but not defined: -leader-elect
Usage of /keda:
  -enable-leader-election
    	Enable leader election for controller manager. Enabling this will ensure there is only one active controller manager.
  -kubeconfig string
    	Paths to a kubeconfig. Only required if out-of-cluster.
  -master --kubeconfig
    	(Deprecated: switch to --kubeconfig) The address of the Kubernetes API server. Overrides any value in kubeconfig. Only required if out-of-cluster.
  -metrics-addr string
    	The address the metric endpoint binds to. (default ":8080")
  -zap-devel
    	Development Mode defaults(encoder=consoleEncoder,logLevel=Debug,stackTraceLevel=Warn). Production Mode defaults(encoder=jsonEncoder,logLevel=Info,stackTraceLevel=Error)
  -zap-encoder value
    	Zap log encoding ('json' or 'console')
  -zap-log-level value
    	Zap Level to configure the verbosity of logging. Can be one of 'debug', 'info', 'error', or any integer value > 0 which corresponds to custom debug levels of increasing verbosity
  -zap-stacktrace-level value
    	Zap Level at and above which stacktraces are captured (one of 'info', 'error').
```

## Expected Behavior
The arg should be `-enable-leader-election` instead of `-leader-elect'` for container in `12-keda-deployment.yaml` file and then it shouldn't go in crashloop.

## Actual Behavior
The argument of container is `-leader-elect` for container in `12-keda-deployment.yaml` file, which is outdated now.

## Steps to Reproduce the Problem

  1. Clone master branch on your local
  2. Install with `helm upgrade --install keda -n keda </path/to/charts/keda>`

## Specifications

  - **KEDA Version:** *2.4.0*
  - **Platform & Version:** *N/A*
  - **Kubernetes Version:** *v1.21.2-eks-0389ca3*
  - **Scaler(s):** *N/A*

**Comment by tomkerkhove** [comment]
Closing as per https://github.com/kedacore/charts/pull/192
