### ISSUE TITLE
Add kube-rbac-proxy image to values.yaml images list

### ISSUE THREAD

**Issue by Giridhar23689** [kedacore/charts#207]
I am trying to internalize all the docker images related to Keda to my private repository. Based on the installation instructions provided for HTTP add on, the docker images mentioned are for operator, scaler and interceptor. The image for kube-rbac-proxy is still being pulled from an external source and hence, my deployment is failing as I have a private K8s cluster with no outbound internet access.

It would be really helpful if we can add the kube-rbac-proxy image to the images section in values.yaml file so that we can set the value in the helm install command.

**Comment by Giridhar23689** [comment]
Yes. Sorry I didn't mention that

**Comment by tomkerkhove** [comment]
Tagging @arschles but curious what you're expecting from us, being able to change the image name through values.yml?

**Comment by Giridhar23689** [comment]
I would like the image repository name to be added in values.yml so that I can run something like helm install --set images.kube-rbac-proxy= xyz and install it .

**Comment by tomkerkhove** [comment]
Are you willing to send a PR for this?

**Comment by Giridhar23689** [comment]
I have raised a PR. Please check.

**Comment by arschles** [comment]
@Giridhar23689 thanks for bringing this up! I just reviewed your PR 👍

**Comment by Giridhar23689** [comment]
@tomkerkhove What is the difference between the kedacore/keda-add-ons-http chart and kedacore/http-add-on chart? 
I am trying to install using kedacore/keda-add-ons-http and the kube-rbac-proxy image is still hardcoded. The installation is failing for me.

**Comment by tomkerkhove** [comment]
There is no `kedacore/http-add-on` chart:

```
~  helm search repo kedacore
NAME                                            CHART VERSION   APP VERSION     DESCRIPTION
kedacore/external-scaler-azure-cosmos-db        0.1.0           0.1.0           Event-based autoscaler for Azure Cosmos DB chan...
kedacore/keda                                   2.5.0           2.5.0           Event-based autoscaler for workloads on Kubernetes
kedacore/keda-add-ons-http                      0.2.0           0.2.0           Event-based autoscaler for HTTP workloads on Ku...
```

The hardcoded image is still there given a new chart was not released yet, but I will do that later today.

**Comment by tomkerkhove** [comment]
Actually, checking with @arschles first if this is OK?

**Comment by Giridhar23689** [comment]
Can you please let me know when the new chart is released?

**Comment by Giridhar23689** [comment]
Can you please provide an ETA for new http-add-on chart release?

**Comment by tomkerkhove** [comment]
@arschles Let me know if it's OK to ship a new version

**Comment by Giridhar23689** [comment]
Any update on the release of http add on Chart. It's been about a month since I have been waiting for a release . Please let me know the ETA.

**Comment by tomkerkhove** [comment]
Sorry but this is due to holiday, checking with Aaron.

**Comment by arschles** [comment]
Sorry about the delay, folks. I lost track of this issue. Yes, we can ship a new version.
