### ISSUE TITLE
Can't have separate values like resources, securityContext for keda-operator and keda-operator-metrics-apiserver containers

### ISSUE THREAD

**Issue by AshutoshNirkhe** [kedacore/charts#232]
## Expected Behavior
We should be able to define different values for parameters like `securityContext`, `resources `etc for `keda-operator` and `keda-operator-metrics-apiserver` containers.

Instead define hierarchy like,
```
.Values.operator.securityContext
.Values.operator-metrics-apiserver.securityContext
```

## Actual Behavior
Parameters like securityContext, resources etc are defined at root level i.e. .values.securityContext , they are applied to both containers keda-operator and keda-operator-metrics-apiserver containers.

## Steps to Reproduce the Problem

None

## Specifications

  - **KEDA Version:** *v2.5.1*
  - **Platform & Version:** *Please elaborate*
  - **Kubernetes Version:** *v1.21.7*
  - **Scaler(s):** *Please elaborate*

**Comment by tomkerkhove** [comment]
That's a fair ask, are you willing to contributing this?

**Comment by tomkerkhove** [comment]
Awesome, thank you! Please make sure it is backwards compatible.

**Comment by AshutoshNirkhe** [comment]
> Awesome, thank you! Please make sure it is backwards compatible.

please have a look at https://github.com/kedacore/charts/pull/239
