### ISSUE TITLE
Add helm chart option for EKS IRSA account

### ISSUE THREAD

**Issue by jcogilvie** [kedacore/charts#233]
Add helm chart support for the [required AWS configuration](https://keda.sh/docs/2.2/troubleshooting/#why-does-keda-operator-error-with-nocredentialproviders) on the ServiceAccount.  

### Use-Case

We're using IRSA for auth inside AWS EKS.  Therefore, the helm chart should offer an out-of-the-box ability to specify the annotation `eks.amazonaws.com/role-arn` if using IRSA.

### Specification

- [ ] Add an optional field for IRSA role arn to the `values.yaml` file

**Comment by tomkerkhove** [comment]
Certainly a valuable ask - Are you willing to contribute this?
