### ISSUE TITLE
1.16 incompatibility, "unknown field x-kubernetes-map-type"

### ISSUE THREAD

**Issue by paul-civitas** [kedacore/charts#241]
When installing the helm chart into a 1.16 cluster I get the following error:

```
error validating data: ValidationError(CustomResourceDefinition.spec.versions[0].schema.openAPIV3Schema.properties.spec.properties.jobTargetRef.properties.template.properties.spec.properties.nodeSelector): unknown field "x-kubernetes-map-type" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.JSONSchemaProps
```

According to the kube reference: https://kubernetes.io/docs/reference/using-api/_print/

"x-kubernetes-map-type" was added in 1.17. So it seems that unlike the documentation states, the earliest compatible version is actually 1.17 and not 1.16.

This is still N-2 of course, but the documentation here states 1.16 or higher: https://keda.sh/docs/2.6/deploy/

So either this is a helm chart compatibility bug, or it's a documentation bug.

**Comment by paul-civitas** [comment]
Seems BC breaking change was made in version 2.5.

**Comment by zroubalik** [comment]
Thanks, we should cover this and bump supported version, @kedacore/keda-maintainers FYI.

**Comment by tomkerkhove** [comment]
Does the field have any value @zroubalik and can we remove it or not?

**Comment by zroubalik** [comment]
@tomkerkhove I think we should modify the docs, and state that we support k8s >= 1.17

I would like to avoid hacking on generated files

**Comment by JorTurFer** [comment]
I agree with @zroubalik 
This file is auto generated

**Comment by tomkerkhove** [comment]
I will send a PR, but we should retro-actively update for v2.5+ and update the release notes - Agreed?

We should also start adding the supported Kubernetes version in our Helm chart and ship a patch version for it to reflect this, agreed?

**Comment by tomkerkhove** [comment]
@zroubalik @JorTurFer Do we patch 2.5.x & 2.6.x?

**Comment by JorTurFer** [comment]
I'd not patch the chart but the docs yes
