### ISSUE TITLE
Support `serviceAccount.labels` directly

### ISSUE THREAD

**Issue by pinkfloydx33** [kedacore/charts#246]
Please consider supporting `serviceAccount.labels` directly.

### Use-Case

The replacement to Azure pod-identity, [Azure workload-identity](https://github.com/Azure/azure-workload-identity), requires a set of annotations and labels on the `ServiceAccount` rather than a single label on the pods. Specifically, it requires a *label*, `azure.workload.identity/use`.

The Keda chart already supports annotations for the `ServiceAccount` via `Values.serviceAccount.annotations`, but does not have a direct label equivalent. It does support adding labels *indirectly* via the helper `keda.labels` which copies labels specified in `Values.additionalLabels`, however these are added to *all* chart-generated resources. I would like to avoid specifying this `ServiceAccount`-specific label in `additionalLabels` and having it leak through to every other resource created by the chart. 

Since there's already a way to get the labels onto the ServiceAccount this is more a nice-to-have than it is a blocker.

**Comment by tomkerkhove** [comment]
Are you willing to contribute this?

**Comment by pinkfloydx33** [comment]
This can technically be closed as the chart now supports AZWI directly. I'm unsure if there are still other cases that warrant labels. The driving issue being the OP has been resolved.

**Comment by tomkerkhove** [comment]
Let's close it and see if it comes back up later on. Thanks for the note.
