### ISSUE TITLE
Split PDB for Operator and Metrics Api & Allow setting replica count for Metrics Api

### ISSUE THREAD

**Issue by mac8005** [kedacore/charts#254]
Replica Count for metrics is not settable [22-metrics-deployment.yaml](https://github.com/kedacore/charts/blob/06600ec4692963db80d4d357c2dcb6c5355d4f1b/keda/templates/22-metrics-deployment.yaml#L11) therefore the `podDisruptionBudget.minAvailable` is not usable as it creates a PDB for the operator AND the Metrics API

## Expected Behavior
- Option to define `podDisruptionBudget` individual for Operator and Metrics APi.
- Option to overwrite `replicas` in Metrics Deployment

## Actual Behavior
- Replica Count for metrics is not settable [22-metrics-deployment.yaml](https://github.com/kedacore/charts/blob/06600ec4692963db80d4d357c2dcb6c5355d4f1b/keda/templates/22-metrics-deployment.yaml#L11) 
- install keda with `--set operator.replicas=2 --set podDisruptionBudget.minAvailable=1` is not feasible as it also creates a PDB for Metrics API 

## Steps to Reproduce the Problem

  1. install keda with `--set operator.replicas=2 --set podDisruptionBudget.minAvailable=1`
  2. PDB for Metrics API is created
  3. Drain Operations will fail, as Metrics API is running with only one replica

## Specifications

  - **KEDA Version:** 2.6.2
  - **Platform & Version:** 
  - **Kubernetes Version:** 1.22 aks
  - **Scaler(s):**

**Comment by tomkerkhove** [comment]
Adding more instances will not help since only 1 can be active at the same time but it would reduce impact though. (see https://keda.sh/docs/latest/operate/cluster/)

Are you willing to contribute this?

**Comment by mac8005** [comment]
> Adding more instances will not help since only 1 can be active at the same time but it would reduce impact though. (see https://keda.sh/docs/latest/operate/cluster/)
> 
> Are you willing to contribute this?
Thank you for the Link!
Ok, so PDB makes no sense for Metrics Api. Yes, I need a PDB for the operator to reduce downtime during cluster Maintenance.
Will open a PR.

**Comment by tomkerkhove** [comment]
Thank you.
