### ISSUE TITLE
Allow pod annotations via Chart

### ISSUE THREAD

**Issue by ncrothe** [kedacore/charts#26]
We would like to automatically add annotations to the controller and metrics pod. This currently does not seem possible via the helm chart. Please add this capability.

Our specific use case would be for kiam instance role annotations for AWS auth.

**Comment by tomkerkhove** [comment]
Makes sense!

**Comment by tomkerkhove** [comment]
With Pod annotations I presume you mean on the Kubernetes deployment?

**Comment by ncrothe** [comment]
Correct. Preferably in flavours for the controller deployment and the metric deployment.
I.e. something in https://github.com/kedacore/charts/blob/master/keda/templates/12-keda-deployment.yaml#L21 and in https://github.com/kedacore/charts/blob/master/keda/templates/22-metrics-deployment.yaml#L19
