### ISSUE TITLE
Obsolete Helm value logging.operator.timeFormat ?

### ISSUE THREAD

**Issue by lsolovey** [kedacore/charts#261]
The [README.md](https://github.com/kedacore/charts/blob/main/keda/README.md) mentions `logging.operator.timeFormat` value with the description:

> Logging time format for KEDA Operator. Allowed values are 'epoch', 'millis', 'nano', or 'iso8601'.

Using keda Helm chart version 2.6.2 - setting this Helm value doesn't seem to make any difference. I don't see it respected by the Helm chart. 

- Is it obsolete and needs to be taken out of README ?
- How can we change the format of time in the logs without this Helm value supported?

## Expected Behavior

Helm value `logging.operator.timeFormat` changes the time format of keda-operator logs.

## Actual Behavior

Helm value `logging.operator.timeFormat` doesn't change the time format of keda-operator logs.

## Specifications

  - **KEDA Version:** 2.6.1 (Helm chart 2.6.2)
  - **Platform & Version:** Docker Desktop Kubernetes
  - **Kubernetes Version:** 1.21.5
  - **Scaler(s):** n/a

**Comment by zroubalik** [comment]
https://github.com/kedacore/keda/blob/main/BUILD.md#keda-operator-logging

This is the source of truth, the helm chart should be updated.

**Comment by tomkerkhove** [comment]
Are you willing to send a PR for this @lsolovey?

**Comment by lsolovey** [comment]
> https://github.com/kedacore/keda/blob/main/BUILD.md#keda-operator-logging
> 
> This is the source of truth, the helm chart should be updated.

Hi @zroubalik, the link above doesn't explain how to change the time format in logs. Do you mean that time format is immutable, and  we just need to remove any mention of `logging.operator.timeFormat` from the Helm chart?

**Comment by zroubalik** [comment]
@lsolovey it seems like it's like that. We rely on https://sdk.operatorframework.io/docs/building-operators/golang/references/logging/ for logging. On a quick check it seems that it doesn't support timeformat. But I might be wrong. Could you please investigate whether there is any advanced option to do so? Thx

**Comment by lsolovey** [comment]
@zroubalik I have no experience with Go, but I'll try to do some research on this. Let me dig into the docs for  Operator Framework logging and Zap.

**Comment by karl-sprig** [comment]
> extraArgs:
>   keda:
>     zap-time-encoding: rfc3339


Just a FYI to future google searchers, the deployment template now has explicitly support for the logging faculties:

https://github.com/kedacore/charts/blob/main/keda/templates/12-keda-deployment.yaml#L67

Via `values.yaml:`

```yaml
logging:
  operator:
    level: debug
```

**Comment by tomkerkhove** [comment]
Yes that is correct. I think we can close this issue?

**Comment by lsolovey** [comment]
@tomkerkhove No, the focus of this issue is to allow customizable timestamp formats in logs.

In other words, to support `logging.operator.timeFormat` Helm value. Please see my detailed comment above from April 28th.

**Comment by lsolovey** [comment]
@tomkerkhove Ah, never mind. Timestamp format is now customizable. It was implemented here:
https://github.com/kedacore/keda/issues/3066

So we can close this one.
