### ISSUE TITLE
apiversion for pdb is behind

### ISSUE THREAD

**Issue by manju4d90** [kedacore/charts#281]
It has been noticed that PDB for both operator and metrics server is at **policy/v1beta1**. Since we see that rest all components are at apiversion **v1**. Could you please let us know when can we expect v1 apiversion for pdb.

## Specifications

  - **KEDA Version:** *2.7.2*
  - **Platform & Version:**
  - **Kubernetes Version:** *v1.22.4 AKS*
  - **Scaler(s):**

**Comment by tomkerkhove** [comment]
Are you willing to send a PR?

**Comment by joebowbeer** [comment]
v1beta deprecated in 1.21, will be removed in 1.25

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125

If KEDA min k8s version is 1.21+, then this can just be changed to v1.

Otherwise, a capabilities check will be needed:

```yaml
{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
```
