### ISSUE TITLE
Chart 2.8.0 bundles outdated CRDs 

### ISSUE THREAD

**Issue by pinkfloydx33** [kedacore/charts#300]
The CRDs in the 2.8.0 chart are not the actual CRDs for 2.8.0. For example the `spec.podIdentity.identityId` field is missing on `[Cluster]TriggerAuthentication`. 

I've double-checked that the CRDs inside the [keda-2.8.0.tgz](https://kedacore.github.io/charts/keda-2.8.0.tgz) file are not the latest ones

This is making migration a bit difficult. We installed Keda (originally) with `crds.install=true`. We have already upgraded to 2.8.0 but were unable to deploy any new trigger authentication resources due to bad CRDs. I patched the CRDs manually so I could deploy them, but they were destroyed on a follow-up `helm upgrade` used to adjust some other values.

## Specifications

  - **KEDA Version:** 2.8.0

**Comment by tomkerkhove** [comment]
That's my fault, I will update them today - Sorry about that :/
