### ISSUE TITLE
[KEDA] Capabilities check needed for Helm file keda/templates/25-metrics-poddisruptionbudget.yaml

### ISSUE THREAD

**Issue by hoepfnerj** [kedacore/charts#325]
The keda Helm chart cannot be deployed on Kubernetes 1.25 due to apiVersion: policy/v1beta1

## Expected Behavior

The keda Helm chart is deployable on Kubernetes 1.25

## Actual Behavior

The PodDisruptionBudget for metrics-apiserver cannot be deployed due to removed apiVersion: policy/v1beta1

## Steps to Reproduce the Problem

  1. set value "podDisruptionBudget.minAvailable: 1"
  2. deploy on Kubernetes 1.25
  3. Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "keda-operator-metrics-apiserver" namespace: "kube-keda" from "": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
│   ensure CRDs are installed first

A solution would be to check cluster capabilities in file keda/templates/25-metrics-poddisruptionbudget.yaml the same way as in keda/templates/13-keda-poddisruptionbudget.yaml

## Specifications

  - **KEDA Version:** 2.8.1
  - **Platform & Version:** *Please elaborate*
  - **Kubernetes Version:** 1.25
  - **Scaler(s):** *Please elaborate*

**Comment by tomkerkhove** [comment]
Are you willing to send a PR?
