### ISSUE TITLE
Use ServiceMonitor instead of PodMonitor in KEDA

### ISSUE THREAD

**Issue by JorTurFer** [kedacore/charts#339]
We are using PodMonitor (Prometheus CRD) to define the scrapping rules in KEDA chart, but both deployments have service indeed, so we should use ServiceMonitor manifests. In cases with multiple KEDA instances, ServiceMonitor allows grouping the metrics by service and Podmonitor doesn't

**Comment by Shaked** [comment]
I can help with this issue

**Comment by JorTurFer** [comment]
Super! Thanks for the help ❤️
