### ISSUE TITLE
Failed to upgrade KEDA to 2.9.0 due to the min kubernetes version requirement in chart

### ISSUE THREAD

**Issue by dogzzdogzz** [kedacore/charts#347]
Our k8s clusters are still in 1.22, trying to upgrade KEDA to 2.9.0 but failed due to the update of min kubernetes version requirement in [this commit](https://github.com/kedacore/charts/commit/1a575338df260789d30144f92f20664292421f7d).

Does KEDA 2.9.0 use any new API group or API version that is only available in k8s 1.23 or later? If not and if the min ver update was just because of lacking resources to maintain and support too many k8s versions, can we just put a supported list note on readme instead of the enforcement in chart? 1.22 has not been EOL yet in most of cloud providers' managed k8s service

## Specifications

  - **KEDA Version:** *2.9.0*
  - **Kubernetes Version:** *1.22*

**Comment by hajdukda** [comment]
Also interested in this. From first glance investigation there is no requirement to force 1.23 in chart.

**Comment by tomkerkhove** [comment]
This is on purpose because Kubernetes v1.22 is not supported - https://keda.sh/docs/2.9/operate/cluster/#kubernetes-compatibility

**Comment by dogzzdogzz** [comment]
@tomkerkhove From the doc I only see the general principle of N-2 supported version, we understand that limiting the supported versions can avoid the maintainer from being overloaded in testing and managing the issues, but do we have to hardcode the limitation in helm chart ? can we let users decide and take their own risk if they want to install it in the k8s version not listed?

Cluster autoscaler also clearly states its supported version in [readme](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler#releases), basically they only commit one version but they didn't put the limitation in helm chart.

We have our own schedule on k8s version upgrades which intentionally does not chase the upstream release frequency because upgrading the master is not as easy as upgrading a single application in cluster while the cluster's scale getting bigger. In our case we just want to upgrade KEDA from 2.8.1 to 2.9.0 for the bug fix for some scaler. With this N-2 limitation in helm chart, we only can fork it and modify the limitation every time we upgrade KEDA version.

**Comment by tomkerkhove** [comment]
The problem is that KEDA depends on Kubernetes and there are features/API versions that we need
