### ISSUE TITLE
Scrape Operator metrics via Prometheus

### ISSUE THREAD

**Issue by ritmas** [kedacore/charts#354]
As of [v2.9.0](https://keda.sh/docs/2.9/operate/prometheus/) `Metrics Server` has been marked as deprecated and new KEDA metrics were introduced which are now accessible via `Operator`.

Question - how can those new metrics be scraped via Prometheus in old way as `prometheus.operator.path` [has been removed](https://github.com/kedacore/charts/pull/337/files#diff-3b4e4c10436059483f20fa5b4b2e507a0bcead63f71af2c02ca41dbff3c8b3adL295) and [12-keda-deployment.yaml](https://github.com/kedacore/charts/blob/main/keda/templates/12-keda-deployment.yaml) doesn't contain any `prometheus.io/...` annotation to hint Prometheus how-to scrape them?

**Comment by tomkerkhove** [comment]
@JorTurFer Can you take a look at this please? I recall you worked on this area a while back (wrt monitor and no monitor)

**Comment by JorTurFer** [comment]
Hi,
You are right, somehow the annotation is missing in the operator, I didn't add the annotations because I thought they were there but no...
@Shaked , could you add them in the PR you are working on? IDK if we should annotate the service or only the pods
