### ISSUE TITLE
Error message deploying keda(v2.9.1) with helm to okd4

### ISSUE THREAD

**Issue by vmm-afonso** [kedacore/charts#365]
So I've been trying to deploy keda (v2.9.1) with helm to okd4 and I've gone through every file inside the repo trying to identify what may be the cause for this error message with no success. I can't seem to find this other resource that "already exist". I modified the kubeVersion to ">=v1.22.0-0" but that shouldn't be the problem. I tried creating a new namespace, adding a new label with "app.kubernetes.io/managed-by: helm" with no success. I can get it via operator-hub but deprecated. I come here seeking help from the council of wizards

Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "clustertriggerauthentications.keda.sh" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "keda"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "keda"

**Comment by zroubalik** [comment]
I am not a helm charts expert, but the error is about clustertriggerauthentications CRD, which is cluster wide resource. 

I recommend you to unistall KEDA, remove all resources, double check that CRDs are not present:

`kubectl get crd | grep keda` 

and install again, btw we have a new version 2.9.2, you can try that.

**Comment by vmm-afonso** [comment]
Ok that might just be the problem. I will follow your recommendation and then let you know it that worked for me. Thank you very much for your help :)

**Comment by vmm-afonso** [comment]
Hey thanks for the help. There were a few resources hanging there that I was able to remove today. That was part of the problem, but I think helm was trying to create or access cluster wide resources (as you suggested) and my user lacked the cluster-admin role privileges needed for it. It's all sorted now. Installed the new version 2.9.2, currently looking for a secret "kedaorg-certs" which seems to be the missing piece and hopefully all works out. Thank again!

**Comment by zroubalik** [comment]
@vmm-afonso the missing certs is a problem in our Helm Charts, please update to 2.9.3. That one should be ok!

**Comment by vmm-afonso** [comment]
Ahh ok, I came across this issue just a few moments ago https://github.com/kedacore/charts/issues/369 and it explained the situation pretty well. Already updated my Chart and everything seems to be working just fine now. Thank you for very much for everything!
