### ISSUE TITLE
Extra objects manifests

### ISSUE THREAD

**Issue by fboula** [kedacore/charts#394]
Enable the possibility to add some extra manifest to the chart by passing a yaml list of k8s manifests. 

This would allow to create any objects you may require to make your keda install to work. This is extremely useful and easy to maintain, an example can be seen in [argo workflow chart](https://github.com/argoproj/argo-helm/blob/main/charts/argo-workflows/values.yaml#L562)

### Use-Case

- Create `ClusterTriggerAuthentication`
- Create secrets required for a `ClusterTriggerAuthentication` 
- Any other resources that would make sense to deploy along the keda chart

If this gets approved, I can work on the pull-request to implement it.

**Comment by mkilchhofer** [comment]
It is really not good practice to deploy CRDs and resources of that CRDs (= an instance) inside one helm release.

See the comment I made in your PR:
- https://github.com/kedacore/charts/pull/395#discussion_r1190861060
