### ISSUE TITLE
`POD_NAMESPACE` environment variable missing

### ISSUE THREAD

**Issue by michemache** [kedacore/charts#403]
## Expected Behavior
Deploying Keda to a different namespace (like kube-addons) do not fail.

## Actual Behavior
Since Keda 2.10.0 deploying to a different namespace (e.g. kube-addons) fails, with this error.

```
2023-03-10T07:30:38Z    ERROR    setup    unable to create certificates secret    {"error": "secrets is forbidden: User \"system:serviceaccount:kube-addons:keda-operator\" cannot create r
esource \"secrets\" in API group \"\" in the namespace \"keda\""}
github.com/kedacore/keda/v2/pkg/certificates.CertManager.ensureSecret
    /workspace/pkg/certificates/certificate_manager.go:148
github.com/kedacore/keda/v2/pkg/certificates.CertManager.AddCertificateRotation
    /workspace/pkg/certificates/certificate_manager.go:66
main.main
    /workspace/cmd/operator/main.go:260
runtime.main
    /usr/local/go/src/runtime/proc.go:250
```

**Reason:** the `POD_NAMESPACE` environment variable is missing

**Temporary fix:** add this to values
```
env:
  - name: POD_NAMESPACE
    value: kube-addons
```

**Long term fix:** add something like this to charts/keda/templates/14-keda-deployment.yaml
```
env:
- name: POD_NAMESPACE
  valueFrom:
    fieldRef:
      fieldPath: metadata.namespace
```

## Steps to Reproduce the Problem

  1. `helm install keda kedacore/keda --namespace kube-addons --version 2.10.0`

## Specifications

  - **KEDA Version:** 2.10.0
  - **Platform & Version:** AWS
  - **Kubernetes Version:** EKS 1.25
  - **Scaler(s):** N/A

**Comment by michemache** [comment]
@tomkerkhove I'm happy to do that, I've prepared a pull request #405

**Comment by tomkerkhove** [comment]
Thank you!
