### ISSUE TITLE
Upgrade to 2.10.0 failed because of missing permissions on secrets

### ISSUE THREAD

**Issue by Aohzan** [kedacore/charts#406]
Hello

Upgrade to 2.10.0 failed because of missing permissions on secrets, I think it's come from `New support for cert-manager for certificate rotation`.

## Expected Behavior

Upgrade from 2.9.4 to 2.10.0 occurs normally

## Actual Behavior

Upgrade failed with this error on keda-operator pod:

```
ERROR    setup    unable to create certificates secret    {"error": "secrets is forbidden: User \"system:serviceaccount:autoscaling:keda-operator\" cannot create resource \"secrets\" in API group \"\" in the na │
│ github.com/kedacore/keda/v2/pkg/certificates.CertManager.ensureSecret
ERROR    setup    unable to set up cert rotation    {"error": "secrets is forbidden: User \"system:serviceaccount:autoscaling:keda-operator\" cannot create resource \"secrets\" in API group \"\" in the namespac │
│ main.main
```

## Steps to Reproduce the Problem

  1. Install Keda Chart with default values in 2.9.4
  2. Upgrade to 2.10.0
  3. 
(it works if I start an install from 2.10.0 directly)

## Specifications

  - **KEDA Version:** 2.9.3 => 2.10.0
  - **Platform & Version:** AWS EKS 1.23.14
  - **Kubernetes Version:** 1.23.14
  - **Scaler(s):** RabbitMQ

**Comment by tomkerkhove** [comment]
Would you mind sharing some more details from your installation please?

For example:
- Role, RoleAssignment,Service account
- KEDA operator deployment

**Comment by Aohzan** [comment]
I only have those parameters:
```yaml
metricsServer.useHostNetwork: true
logging.operator.level: info
logging.metricServer.level: 0
```
everything else is default chart values

**Comment by michemache** [comment]
@Aohzan have a look here https://github.com/kedacore/charts/issues/403 as you are deploying to the namespace `autoscaling` and not to the default one.

**Comment by Aohzan** [comment]
ok thank you it's the same problem
