### ISSUE TITLE
Keda-metrics-apiserver connection error 

### ISSUE THREAD

**Issue by DANic-git** [kedacore/charts#409]
keda-metrics-apiserver connection error when cluster name is not cluster.local
Because cluster name are hardcoded in manifests
https://github.com/kedacore/charts/blob/main/keda/templates/22-metrics-deployment.yaml#L113
https://github.com/kedacore/charts/blob/main/keda/templates/43-cert-manager-keda-tls-certificate.yaml#L17
## Expected Behavior
`I0315 09:58:04.878126       1 provider.go:84] keda_metrics_adapter/provider "msg"="Connection to KEDA Metrics Service gRPC server has been successfully established" "server"="keda.infra.svc:9666"`

## Actual Behavior

```
Err: connection error: desc = "transport: Error while dialing: dial tcp: lookup keda.infra.svc.cluster.local on 169.254.25.10:53: no such host"
W0315 09:46:50.644544       1 logging.go:59] [core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {
  "Addr": "keda.infra.svc.cluster.local:9666",
  "ServerName": "keda.infra.svc.cluster.local:9666",
  "Attributes": null,
  "BalancerAttributes": null,
  "Type": 0,
  "Metadata": null
```

## Steps to Reproduce the Problem

  1. Install KEDA by helm chart

## Specifications

  - **KEDA Version:** *2.10.0*
  - **Kubernetes Version:** *1.25.7*

**Comment by tomkerkhove** [comment]
This should be fixed in https://github.com/kedacore/charts/pull/399
