### ISSUE TITLE
Version should be updated to 1.4.0 not to 1.3.2

### ISSUE THREAD

**Issue by zroubalik** [kedacore/charts#42]
@SatishRanjan when you did release, you haven't updated version to 1.4.0. The PR should be checked and be approved by at least one person to avoid these kind of problems. 

https://github.com/kedacore/charts/blob/345ae4384beaef78aa4a8d9e56edbb0dbde62a7d/keda/Chart.yaml#L7-L11

**Comment by tomkerkhove** [comment]
Shall we publish a v1.4.1 for Helm chart?

Well technically we can still:
- Ship chart 1.4.0 with app 1.4.0
- Ship chart 1.3.3 to change app back to 1.3.0

**Comment by tomkerkhove** [comment]
Happy to PR if we agree on it

**Comment by ahmelsayed** [comment]
Yes I think that makes sense @tomkerkhove!

**Comment by SatishRanjan** [comment]
@zroubalik I did notice that when I saw the version but it was automatically updated to 1.3.2 from 1.3.1, so I thought the helm chart versioning works separate that of KEDA.

**Comment by SatishRanjan** [comment]
Good to know it for the next release onwards.

**Comment by tomkerkhove** [comment]
That's ok.

We had a few changes in this repo as well that have to be shipped, that's why. Will patch it on Thursday or so.

**Comment by tomkerkhove** [comment]
Actually just went for it.
