### ISSUE TITLE
Security vulnerabilities found in Keda by Prisma Cloud container scan

### ISSUE THREAD

**Issue by kalpesh6331** [kedacore/charts#424]
## Description

We are using Keda to achieve custom metrics based HPA into our application
This application is mission critical and has been running in production since couple months
As a part of CIS benchmarks, we need to run different scans on the runtime
Prisma Cloud (from PaloAlto networks) has detected following vulnerabilities

We would like to know if these can be fixed or already fixed in any future releases
If it is fixed via configuration (changes in helm values), would it affect any functionality or working of Keda?

## Vulnerabilities:

1. image: keda:2.8.1
   description: Use PIDs cgroup limit
   severity: High

2. image: keda-metrics-apiserver:2.8.1
   description: Mount container's root filesystem as read only
   severity: High

3. image: keda-metrics-apiserver:2.8.1
   description: Use PIDs cgroup limit
   severity: High

## Specifications

  - **KEDA Version:** *2.8.2*
  - **Kubernetes Version:** *1.23*

**Comment by kalpesh6331** [comment]
Could anyone please update on this?

**Comment by zroubalik** [comment]
You can check the latest patch release for 2.8 if it fixes these problems: https://github.com/kedacore/charts/releases/tag/v2.8.4 But we don't plan to maintain this version anymore, we suggest you to update to a newer version.

**Comment by kalpesh6331** [comment]
Sure, Thank you for the update! @zroubalik
