### ISSUE TITLE
Add ability to deploy NetworkPolicies for all 3 components of KEDA

### ISSUE THREAD

**Issue by mkilchhofer** [kedacore/charts#445]
In all our environments on AWS EKS / Azure AKS / VMware tanzu we drop all network traffic between all Pods by default. Every Pod needs to have a related NetworkPolicy resource in which every connection is defined.

### Use-Case

I'd like to contribute NetworkPolicy resource for all 3 components.

### Specification

- Add 3 networkpolicy.yaml, one for each component

**Comment by zroubalik** [comment]
@mkilchhofer sounds reasonable, we will be happy to have this contribution, thanks!

**Comment by mkilchhofer** [comment]
It was implemented in this PR:
- https://github.com/kedacore/charts/pull/558
