### ISSUE TITLE
Some Helm releases are incorrectly packaged

### ISSUE THREAD

**Issue by MShekow** [kedacore/charts#461]
If you compare the following packaged Helm charts with other Helm charts, you will notice that an incorrect Windows-style directory separator (`\` instead of `/`) has been used, which can cause problems when unpacking or using the chart:

- https://kedacore.github.io/charts/keda-1.4.0.tgz
- https://kedacore.github.io/charts/keda-1.3.2.tgz
- https://kedacore.github.io/charts/keda-1.3.0.tgz

Could these be repackaged and re-uploaded?

**Comment by tomkerkhove** [comment]
We don't support KEDA 1 anymore, is there a reason why you cannot upgrade to 2?

**Comment by MShekow** [comment]
We are not using these old KEDA versions ourselves either. We just noticed the problem when using [charts-syncer](https://github.com/bitnami-labs/charts-syncer/) which, by default, synchronizes _all_ charts, but has trouble syncing these specific ones, because they are broken. The quick fix would probably be excluding these versions from the index.yaml file.

**Comment by zroubalik** [comment]
I think we can do that, WDYT @kedacore/keda-helm-contributors ?

**Comment by tomkerkhove** [comment]
Everything is possible :D Just wondering if it's worth it.

Are you open to contribute this, @MShekow?

**Comment by MShekow** [comment]
IMO it's much simpler to just fix the 3 tar.gz files. It's really just extracting them (with a tool that can handle Windows-style backslashes, e.g. 7-zip on Windows) and re-tarring it (on Linux/WSL with standard `tar`).

This way, the index can still contain _all_ charts.

**Comment by tomkerkhove** [comment]
Certainly, that would be awesome, thank you!
