### ISSUE TITLE
keda metrics-apiserver Deployment is rendered with annotation with empty value

### ISSUE THREAD

**Issue by acobaugh** [kedacore/charts#488]
Helm chart fails to render correctly when `prometheus.metricServer.enabled` = `true`

The [template](https://github.com/kedacore/charts/blob/main/keda/templates/metrics-server/deployment.yaml#L43C71-L43C71) is still using a value that was removed [here](https://github.com/kedacore/charts/pull/432/files#diff-e4bce03cbb43ee0d96175c3b795628766459c5829a05d6f2c42e6b90d0f7b303L154)

## Expected Behavior

Helm chart for keda renders correctly

## Actual Behavior

```error validating "": error validating data: unknown object type "nil" in Deployment.spec.template.metadata.annotations.prometheus.io/path```

## Steps to Reproduce the Problem

  1. Install keda chart 2.11.0 with the following: ```helm template keda kedacore/keda --skip-crds --set prometheus.metricServer.enabled=true --set additionalAnnotations.dummy=value```

## Specifications

  - **KEDA Version:** 2.11.0
  - **Platform & Version:** n/a
  - **Kubernetes Version:** n/a
  - **Scaler(s):** n/a

**Comment by emctl** [comment]
Had a quick look but was unfortunately not able to reproduce successfully via:
```
helm repo add kedacore https://kedacore.github.io/charts 
helm repo update
helm search repo kedacore/keda
NAME                            CHART VERSION   APP VERSION     DESCRIPTION                                       
kedacore/keda                   2.11.1          2.11.1          Event-based autoscaler for workloads on Kubernetes

helm template keda kedacore/keda --skip-crds --set prometheus.metricServer.enabled=true --set additionalAnnotations.dummy=value
```

**Comment by emctl** [comment]
Based on [this](https://github.com/kubernetes-sigs/metrics-server/blob/master/docs/command-line-flags.txt) I think its safe to confirm that the [linked pr ](https://github.com/kedacore/charts/pull/432/files#diff-e4bce03cbb43ee0d96175c3b795628766459c5829a05d6f2c42e6b90d0f7b303L154) just need to remove that extra field.  
PR [here](https://github.com/kedacore/charts/pull/494)
