### ISSUE TITLE
KEDA replicaCount  (Question not bug)

### ISSUE THREAD

**Issue by oronboni** [kedacore/charts#50]
One of the values is replicaCount: 1.
Can we change it to 2 (or any number higher than 1) based on the current architecture ?

**Comment by tomkerkhove** [comment]
I think this is safe, right @zroubalik ?

**Comment by zroubalik** [comment]
No, you cannot run multiple replicas of KEDA, the controllers would interfere between each other and wouldn't bring any benefit.

**Comment by tomkerkhove** [comment]
In that case we might want to remove that parameter to avoid misconfiguration, ok for you?

**Comment by zroubalik** [comment]
@tomkerkhove completely fine!
