### ISSUE TITLE
Keda Metrics Server prometheus metrics port doesn't work 

### ISSUE THREAD

**Issue by northys** [kedacore/charts#504]
After the upgrade to keda version which introduced third pod (there used to be only 2 pods IIRC) we started having issues with scrapping metrics from keda metrics server although we have enabled it using following config.

```
prometheus:
  metricServer:
    enabled: true
    serviceMonitor:
      enabled: true
```

## Expected Behavior

Connection to metrics server service at port 8080 (or specified) returns metrics at path /metrics.

## Actual Behavior

Connection to metrics-server:8080 results in connection refused.

## Steps to Reproduce the Problem

  1. deploy keda with provided config
  2. HTTP GET for metrics server service at port 8080 results in following error in prometheus `Get "http://192.168.73.158:8080/metrics": dial tcp 192.168.73.158:8080: connect: connection refused`
  3. webhooks and operator monitoring endpoint works just fine, only metrics is broken

## Specifications

  - **KEDA Version:** 2.11.0
  - **Platform & Version:** 
  - **Kubernetes Version:** EKS 1.27
  - **Scaler(s):** -

**Comment by trampfox** [comment]
The issue you are describing sounds similar to [the one](https://github.com/kedacore/charts/issues/499) we encountered after upgrading to the version 2.11.1 of the charts.

We were able to resolve the issue by upgrading to version 2.11.2: https://github.com/kedacore/keda/releases/tag/v2.11.2
