### ISSUE TITLE
Add support for metricRelabelings to Pod and Service monitors 

### ISSUE THREAD

**Issue by pragmaticivan** [kedacore/charts#514]
https://github.com/prometheus/prometheus/issues/5200

__name__ is not available in relabelings.

### Use-Case

To perform something like:
```
- sourceLabels: [__name__]
      regex: ^keda_scaler_errors$
      targetLabel: newrelic_metric_type
      action: replace
      replacement: counter
```

it would need to go under metricRelabelings instead.

**Comment by pragmaticivan** [comment]
I can also take this one if accepted.

**Comment by pragmaticivan** [comment]
cc @JorTurFer  I can take this one if accepted

**Comment by JorTurFer** [comment]
Yeah, I think it's a good addition. Not setting them as default keeps current behavior and adding them can extend current options
