### ISSUE TITLE
[http-add-on] admin-port in http-add-on-operator does not exist anymore when using latest commit

### ISSUE THREAD

**Issue by jocelynthode** [kedacore/charts#516]
The operator cannot start when using latest http-add-on commit

This is due to https://github.com/kedacore/charts/blob/main/http-add-on/templates/deployment-operator.yaml#L53 which apparently does not exist anymore in latest operator code and should thus be removed from the chart manifests as well as its variable.

## Expected Behavior
The operator should start

## Actual Behavior
The operator crashes with the help message

## Steps to Reproduce the Problem

  1. Use commit `0321ee0` from keda-http-add-on in helm chart
  2. Operator crashes

**Comment by jocelynthode** [comment]
@JorTurFer: Would you like me to submit a PR to remove this `admin-port` or did I misunderstand why it's not working?

**Comment by JorTurFer** [comment]
> @JorTurFer: Would you like me to submit a PR to remove this `admin-port` or did I misunderstand why it's not working?

I'm reviewing the whole chart to be sure that it works

**Comment by JorTurFer** [comment]
I think that [this PR](https://github.com/kedacore/charts/pull/523) aligns the helm chart with latest version. Once it's merged you can use it (pulling it and deploying it locally or building your own chart) if you want to try it.

I have added a validation check for [the interceptor ScaledObject](https://github.com/kedacore/charts/pull/523/files#diff-d4f925f2bdf778e42d06df2106e512f783f970352207a2b57deb2004b89d12caR115-R126), so I hope that the issue won't come back as a regression in the future 🤞

**Comment by jocelynthode** [comment]
Thanks, yes it looks like it :)
