### ISSUE TITLE
Use existing metrics server?

### ISSUE THREAD

**Issue by aleveille** [kedacore/charts#517]
Would it be possible to use an existing metrics server?

### Use-Case

We have an existing metrics-server as part of our APM solution and we do not want to have to remove that server to deploy Keda.

### Specification

- Allow disabling the deployment of Keda's metrics-service. Something like adding `if` statements around resources defined in `charts/keda/templates/metrics-server`
- Allow specifying a custom metrics-server URL

### Additional notes

I'm am very comfortable with Helm so I have already forked the repo and will be working on this. However, I need the input of Keda's team on whether this proposal is sensible and could work.

**Comment by aleveille** [comment]
Related to https://github.com/kedacore/keda/issues/470

**Comment by tomkerkhove** [comment]
This is not supported today. If you can't use KEDA's metric server, you can't use KEDA. See https://keda.sh/docs/2.11/faq/#kubernetes
