### ISSUE TITLE
KEDA v2 Support

### ISSUE THREAD

**Issue by jacobhjkim** [kedacore/charts#55]
It would be great to have the KEDA v2 Helm Chart as a separate branch. Is there any plan on supporting KEDA v2 in this charts repository?

**Comment by tomkerkhove** [comment]
Yes but we are still working on v2 itself so have not changed our charts yet to align with them.

**Comment by tomkerkhove** [comment]
@zroubalik Feel free to list required changes here so we can make them accordingly.

**Comment by tomkerkhove** [comment]
Chart has been updated and available, can you give it a try please @jacobhjkim ?

**Comment by jacobhjkim** [comment]
Awesome I will close this issue.
