### ISSUE TITLE
Sidecar containers for Keda operator

### ISSUE THREAD

**Issue by lpetrazickisupgrade** [kedacore/charts#607]
Configuration parameters for defining additional sidecar and init containers for Keda operator

### Use-Case

I typically use a sidecar container to manage AWS IAM auth, which is useful for Postgres and similar Keda scalers. For RDS Postgres specifically, the sidecar could use AWS IAM to get a temporary auth token and write that token to a standard PGPASS file on a shared volume. Keda Operator already supports mounting extra volumes, so being able to specify extra containers is the missing part of config options for this

### Specification

- [ ] `extraContainers` configuration parameter for regular sidecar containers
- [ ] `extraInitContainers` configuration parameter for sidecar containers that run at pod startup

**Comment by JorTurFer** [comment]
I see this useful, but maybe you can't use the PGPASS despite if it's mounted. I have no idea about how it works being honest, but take into account that KEDA does some validation of the trigger configuration, so maybe the validation fails although the file is there
