### ISSUE TITLE
Cannot create resource "customresourcedefinitioins"

### ISSUE THREAD

**Issue by gardnerdev** [kedacore/charts#61]
During installing KEDA by using `helm install keda kedacore/keda` I've got following error:
> Error: failed to install CRD crds/keda.k8s.io_scaledobjects_crd.yaml: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "u-f6efqrxwsu" cannot create resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope

**Comment by tomkerkhove** [comment]
It looks like your user does not have permissions to do so, is this an RBAC-enabled cluster?

**Comment by gardnerdev** [comment]
@tomkerkhove - can it be slightly modified to operate only on namespace area? not cluster?
> rules:
> - apiGroups: [""]
>   resources: ["pods", "persistentvolumeclaims", "secrets", "podtemplates", "serviceaccounts", "services", "replicationcontrollers", "endpoints", "configmaps", "events", "limitranges"]
>   verbs: ["create", "get", "update", "patch", "delete", "list", "watch"]
> - apiGroups: [""]
>   resources: ["namespaces"]
>   verbs: ["get"]
> - apiGroups: ["apps"]
>   resources: ["deployments", "replicasets", "daemonsets", "statefulsets", "controllerrevisions"]
>   verbs: ["create", "get", "update", "patch", "delete", "list", "watch"]
> - apiGroups: ["extensions"]
>   resources: ["ingresses", "deployments"]
>   verbs: ["create", "get", "update", "patch", "delete", "list", "watch"]
> - apiGroups: ["batch"]
>   resources: ["jobs", "cronjobs"]
>   verbs: ["create", "get", "update", "patch", "delete", "list", "watch"]

**Comment by zroubalik** [comment]
`CustomResourceDefinitions` requires admin permissions, those are cluster-wide resources.

**Comment by tomkerkhove** [comment]
Can we close this issue @gardnerdev ?
