### ISSUE TITLE
Allow metrics-server non-kube-system RBAC (+ClusterRole) deployment 

### ISSUE THREAD

**Issue by Rotzke** [kedacore/charts#645]
Hi!

We have a pretty rare case in our company which is still spread across clusters out there. In a situation where you can not deploy to kube-system namespace it is not possible to deploy the chart, because metrics-server needs access to 
extension-apiserver-authentication ConfigMap, thus a RoleBinding should be deployed to kube-system in order to achieve this: https://github.com/kedacore/charts/blob/43b0f516e0d101c18830d06126700916c029712b/keda/templates/metrics-server/clusterrolebinding.yaml#L24 
A possible solution here would be to add a ClusterRole with same permissions as the extension-apiserver-authentication-reader Role and make it optional if kube-system deployment is not possible. I have already forked the chart and am ready to create a MR if it could be approved. Maybe you have other suggestions, would be really glad to hear them.

Looking forward to hearing from you!

Nils.

**Comment by robervexcel** [comment]
I look forward to this application

**Comment by rupertgti** [comment]
I look forward to this application
