### ISSUE TITLE
The "scaledjobs.keda.sh" CRD have too long metadata.annotations

### ISSUE THREAD

**Issue by ivanfavi** [kedacore/charts#653]
We are encountering an issue when attempting to deploy the Keda Helm chart that includes a CustomResourceDefinition (CRD) for scaledjobs.keda.sh. The deployment fails with the following error message:

> The CustomResourceDefinition "scaledjobs.keda.sh" is invalid: metadata.annotations: Too long: must have at most 262144

We would appreciate guidance on how to resolve this issue or if there are any recommended changes to the Helm chart or CRD to address this limitation. 

## Expected Behavior

The Keda Helm chart should deploy successfully, including the scaledjobs.keda.sh CustomResourceDefinition, without encountering errors related to metadata annotations. 

## Actual Behavior

![image](https://github.com/kedacore/charts/assets/46492472/2667576e-8199-443d-9148-87d5427d69f3)

## Steps to Reproduce the Problem

  1.Install CRDs using kubectl

```
kubectl -n keda apply -f keda-2.14.0-crds.yaml
customresourcedefinition.apiextensions.k8s.io/cloudeventsources.eventing.keda.sh configured
customresourcedefinition.apiextensions.k8s.io/clustertriggerauthentications.keda.sh configured
customresourcedefinition.apiextensions.k8s.io/scaledobjects.keda.sh configured
customresourcedefinition.apiextensions.k8s.io/triggerauthentications.keda.sh configured
The CustomResourceDefinition "scaledjobs.keda.sh" is invalid: metadata.annotations: Too long: must have at most 262144 bytes

```

## Specifications

  - **KEDA Version:** *2.14.0*
  - **Kubernetes Version:** *1.28.9*

**Comment by ivanfavi** [comment]
@Encounter77 I found this issue in both deployments methods, also with the helm chart.

**Comment by zroubalik** [comment]
Just use server side apply as it is mentioned in the docs https://keda.sh/docs/2.14/deploy/#install-2

**Comment by ivanfavi** [comment]
This [comment](https://github.com/kedacore/keda/issues/4740#issuecomment-2009511385) made the trick. Thank you so much for your help @zroubalik  @Encounter77 :pray:
