### ISSUE TITLE
Missing PDB for http addon interceptors

### ISSUE THREAD

**Issue by abatilo** [kedacore/charts#658]
There is no pod disruption budget on the http addon interceptors, which means that during node rollover, there might not be any interceptors available to add requests to its queue. Since the queues themselves are in memory, that means that there would be dropped requests.

Could we add a PDB to that replicaset?

**Comment by zroubalik** [comment]
@abatilo are you willing to contribute this?

**Comment by abatilo** [comment]
Hi @zroubalik! I am willing to contribute this!

https://github.com/kedacore/charts/pull/662
