### ISSUE TITLE
Incorrect apiGroup in keda-clusterrole

### ISSUE THREAD

**Issue by leonfibal** [kedacore/charts#71]
Yesterday I deployed keda using helm chart with version 2.0.0-beta.1.1. Now my keda operator and keda metrics apiserver log errors:
```
Failed to list *v1alpha1.ScaledObject: scaledobjects.keda.sh is forbidden: User "system:serviceaccount:keda:keda-operator" cannot list resource "scaledobjects" in API group "keda.sh" at the cluster scope
```
```
scaledobjects.keda.sh is forbidden: User \"system:serviceaccount:keda:keda-operator\" cannot list resource \"scaledobjects\" in API group \"keda.sh\" at the cluster scope
```

I think the problem is here (https://github.com/kedacore/charts/blob/master/keda/templates/10-keda-clusterrole.yaml#L50):
```yaml
- apiGroups:
  - keda.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
```

**Comment by zroubalik** [comment]
@leonfibal good catch, thanks! The Chart need still some polishing.

**Comment by golgoth31** [comment]
Hi,
There is also a problem on the resource "deployments/scale", it should be added to the clusterrole:
{"level":"error","ts":1600850002.1993313,"logger":"controller","msg":"Reconciler error","reconcilerGroup":"keda.sh","reconcilerKind":"ScaledObject","controller":"scaledobject","name":"xxx","namespace":"xxx","error":"deployments.apps \"image-converter\" is forbidden: User \"system:serviceaccount:keda:keda-operator\" cannot get resource \"deployments/scale\" in API group \"apps\" in the namespace \"scaling\"","stacktrace":"xxxx"}

thank you for your work!
