### ISSUE TITLE
Wrong Renew Before default values in cert-manager integrations leads to certificate expired

### ISSUE THREAD

**Issue by tete17** [kedacore/charts#710]
After running Keda stably for over 2 years with the cert-manager integration we found a subtle but important bug that essentially turns into a exploding bomb after 2 years :bomb:. Our Certificate authority expired before the lead certificate had a chance to be renewed

When enabled, KEDA instanciates 2 certificates as part of a custom PKI infra to be able to communicate with the control plane using tls. In particular it creates the following:
 * A Root CA:
   * Duration: 1 year (fixed)
   * RenewBefore: 1 month (fixed)
 * A Leaf CA, signed by the Root CA:
   * Duration: 1 year (configurable)
   * RenewBefore: 8 months (configurable)

What we saw after 2 years of continual usage is described in the attached picture but I will try to summarize it in words.

![image](https://github.com/user-attachments/assets/bb932fa0-0bac-42ee-912b-ea406527c865)

Timeline: 
  * 17/08/24 => Lead certificate gets renewed as usual procedure
    * This will be valid for a year and won't get renewed again until 4 months have passed.
  * 21/10/24 => Root certificate gets renewed
    * The new one is valid for a year while the old one is still valid for another 30 days
  * 21/11/24 => The old CA expires. 

That last event is the problematic. Technically both certs are still valid but the leaf certificate has been signed by a cert that is expired. This leads to the communication between the metrics pod and the controller to be broken. This is very dangerous as in our case it prevented our workloads to scale correctly  as the system was unable to detect the metrics correctly.

To make the matter even more complicated cert-manager is 100% unavare. As far as the controller is concerned both certs are generated, valid and signed. No matter how many times you restart the pods nothing changes. The only solution at this point is to manually renew the leaf cert, either by manually removing the underlying secret or through the cert-manager apis.

> [!CAUTION]
> CC: @jeffhollan @JorTurFer @zroubalik @wozniakjan 
> I ask for the keda mantainers to please pay attention to this urgently as I suspect many people use the default config like we do and have a ticking bomb in their systems. All that is needed for this to trigger is the following config.

```yaml
certificates:
  certManager:
    enabled: true
```

At my company we are lucky enough to deploy very aggressively and stay up to date with release so we may be one of the first once to notice and diagnose the problem. 

Thankfully the scale from 0 to 1 worked fine as it is independent but since that point the work is being picked up by the HPA it wasn't unable to continue.

## Expected Behavior

There are many lessons learn for me. In regards to keda, I think the chart should always ensure that, the `renewBefore` field of the Root CA should always be bigger than the usage duration of the leaf certificate (i.e. `duration` - `renewBefore`). This ensures that there will be at least a renewal of the leaf certificate in between a new root ca being issued and the old CA being expired.

Furthermore the Root CA should probably last longer than the leaf certificate. Looking at `nginx-ingress`, another project with a similar setup their values are 5 years for the root and 1 year for the leaf. Furthermore they allow the default renewBefore value of 2/3 of the duration. This makes them safe and robust with plenty of time to switch to the new CA.

I will also open up a discussion with the cert-manager team if it makes sense to consider a certificate as invalid if the ca is expired and maybe renew it as well.

## Actual Behavior

Our Root CA expired faster than our leaf certificate could renew itself-

## Steps to Reproduce the Problem

  1. Deploy the chart with 
```yaml
certificates:
  certManager:
    enabled: true
```
  2. Wait for 2 years... (I know a bit of an obscure scene)
  3. The metrics pod will log thing similar to this
```
W1120 15:26:04.275111       1 logging.go:55] [core] [Channel #1 SubChannel #2]grpc: addrConn.createTransport failed to connect to {Addr: "10.0.16.17:9666", ServerName: "keda-operator.keda.svc.cluster.local:9666", }. Err: connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2024-11-20T15:26:04Z is after 2024-11-20T03:13:23Z"
```

## Specifications

  - **KEDA Version:** 2.16.0
  - **Platform & Version:** AKS + cert-manager 
  - **Kubernetes Version:** 1.30.5
  - **Scaler(s):** Rabbitmq, although it really doesn't matter as it is a general problem

**Comment by wozniakjan** [comment]
I think you are right, the fact that the leaf cert is generated every 2 months but root CA can sign a month before its own expiration seems like a bug. The root CA should probably renew 3 months before its own expiry to be on the safe side.

**Comment by wozniakjan** [comment]
imho https://github.com/kedacore/charts/pull/711 should fix this but I will wait for someone to verify my logic :)
