### ISSUE TITLE
Add ServiceMonitor to pull metrics to Prometheus

### ISSUE THREAD

**Issue by oronboni** [kedacore/charts#80]
I saw in the code that you add /metric endpoint.
ServiceMonitor yaml required in order to define Prometheus to pull metrics from KEDA pods.

**Comment by tomkerkhove** [comment]
What do you think @ahmelsayed @tbickford? What about automatic discovery through annotations?

**Comment by tomkerkhove** [comment]
I've looked over it given we already have this available: https://github.com/kedacore/charts/blob/master/keda/templates/26-metrics-podmonitor.yaml

You can use it when opting in through `prometheus.enabled` & `prometheus.podMonitor.enabled`.

We've shipped a fix for it, can you please try https://github.com/kedacore/charts/releases/tag/v2.0.0-rc2?

**Comment by mlushpenko** [comment]
Seems to work for me with PodMonitor.
![image](https://user-images.githubusercontent.com/2006610/111990298-7a741700-8b13-11eb-99e5-447afeb0859e.png)


Just values are different:
```
prometheus:
  metricServer:
    enabled: true
    podMonitor:
      enabled: true
```

**Comment by tomkerkhove** [comment]
@oronboni this has been available for a while, let me know if you have issues
