### ISSUE TITLE
Helm chart v2.0.0-rc2 fails to install on fresh k8s 1.18.8

### ISSUE THREAD

**Issue by rhummelmose** [kedacore/charts#88]
Attempting to install the chart fails with error

```console
➜  duah-infrastructure git:(master) ✗ helm install keda kedacore/keda --version 2.0.0-rc2 --namespace keda       
Error: rendered manifests contain a resource that already exists. Unable to continue with install: CustomResourceDefinition "scaledjobs.keda.sh" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "keda"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "keda"
```
<img width="1538" alt="screenshot" src="https://user-images.githubusercontent.com/620878/97165574-378c5e00-1784-11eb-84de-248a92c472e8.png">

## Expected Behavior
It is able to install on a fresh cluster

## Actual Behavior
It does not install

## Steps to Reproduce the Problem

  1. Attempt to install

## Specifications

  - **KEDA Version:** 2.0.0-rc2
  - **Platform & Version:** Azure, AKS, fresh as of 26/10/2020
  - **Kubernetes Version:** 1.18.8

**Comment by tomkerkhove** [comment]
I'll take a look at this and have created #87 to avoid this in the future

**Comment by RemiGaudin** [comment]
Interestingly I have the same issue with version 2.0.0-rc2, but it's working fine with version 2.0.0-rc

**Comment by tomkerkhove** [comment]
@ahmelsayed do you have bandwidth to help here?

**Comment by jeffhollan** [comment]
Discussed in standup - hoping to get rid of the problem.  @tomkerkhove shipped `2.0.0-rc3` works now, but it has helm 2.  Need to fix so `2.0.0` can use helm 3 and not support helm 2.

@TsuyoshiUshio / @ahmelsayed let me know if you can help look at this. I may be able to spend some cycles tonight as well

**Comment by arschles** [comment]
I can give a hand here.

**Comment by tomkerkhove** [comment]
Thanks @arschles!

**Comment by rhummelmose** [comment]
Awesome guys. @arschles let me know if you can't find the time and I'll try to fix it during the weekend.

**Comment by jeffhollan** [comment]
Can confirm that 2.0.0-rc3 works, but it isn't published to the index so had to clone. Let me clean it up a little and publish

**Comment by tomkerkhove** [comment]
Thanks for the write-up, if I get it correctly it's just due to Helm 3, right?

**Comment by kainwei** [comment]
I am not sure what will happened in Helm2, but in my case, yes, I used Helm 3.
